parameters:
    claude_api_key: '%env(CLAUDE_API_KEY)%'
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Service\AIRecommendationService:
        arguments:
            $apiKey: '%claude_api_key%'
            $httpClient: '@http_client'
            $logger: '@logger'
    
